config/routes.rb
Rails.application.routes.draw do
  get 'personal' ,  to:  'static_pages#personal'
  get 'notes' , to: 'static_pages#notes'
  get 'diary' ,  to: 'static_pages#diary'
  post 'auth' , to: "static_pages#auth"
  resources :thoughts,only:[:edit,:create,:update,:destroy]
  resources :users do
    member do
      get :following,:followers
    end
  end
  resources :relationships, only: [:create,:destroy]
  post 'login' ,  to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  root 'static_pages#home'

  get 'help',   to:'static_pages#help'

  get 'about',  to: 'static_pages#about'

  get 'contact', to: 'static_pages#contact'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless right_user(@user) %>
<div id="follow_form" class="profile-userbuttons">
  <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
  <% else %>
  <%= render 'follow'  %>
  <% end %>
</div>
<% end %>

app/views/shared/_following_list.html.erb
<div class="following_user_list">
  <ol class="move_list">
    <% @user.followings.take(10).each do |user| %>
      <%= render 'shared/friends_list', user: user  %>
    <% end %>
  </ol>
</div>

app/views/shared/_friends_list.html.erb
<li class="user_list_item"><span>
<%= image_tag(user.picture? ? user.picture.url : asset_path("default.jpg"), class: "img-responsive ",
 alt: user.name,size: "20x20") %>
  </span>
  <span class="user_name">
    <div> <%= link_to "#{user.name.capitalize}",user_path(user) %></div>

    </span>
</li>

app/views/shared/_password.html.erb
<%= form_tag auth_path do %>
<%= label_tag "re-enter password" %>
<%= password_field_tag "password"%>
<%= submit_tag 'Submit' %>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="profile-sidebar">
  <!-- SIDEBAR USERPIC -->
  <div class="profile-userpic">
    <% if current_user.picture?  %>
    <%= image_tag(current_user.picture.url, class: "img-responsive ", alt: " Profile Picture") %>
    <% else %>
    <%= image_tag(asset_path("default.jpg"), class: "img-responsive ", alt: "Profile Picture",size: "200x200") %>
    <% end %>
  </div>
  <!-- END SIDEBAR USERPIC -->
  <!-- SIDEBAR USER TITLE -->
  <div class="profile-usertitle">
    <div class="profile-usertitle-name">
      <%= @user.name  %>
    </div>

    <div class="profile-usertitle-job">
      <% if option=@user.about %>
      <%= option %>
      <% elsif  right_user(@user)%>
      <%= link_to "add option", edit_user_path(@user)  %>
      <% else %>
      Beginner
      <% end %>
    </div>
  </div>
  <!-- END SIDEBAR USER TITLE -->
  <!-- SIDEBAR BUTTONS -->
  <div class="thought-count">
    <%= @user.thoughts.where("category= ? ","Home").count  %> thoughts
  </div>
  <div>
    <%= render 'shared/follow_form'  %>
  </div>
  <!-- END SIDEBAR BUTTONS -->
  <!-- SIDEBAR MENU -->
  <div class="profile-usermenu">
    <ul class="nav">
      <% if right_user(@user) %>
      <li >
        <%= link_to users_path do %>
        <i class="glyphicon glyphicon-globe"></i>
        Users
        <% end %>
      </li>
      <li>
        <%= link_to edit_user_path(current_user) do %>
        <i class="glyphicon glyphicon-user"></i>
        Profile
        <% end %>
      </li>
      <% end %>
<!--       <li>
        <a href="#" target="_blank">
          <i class="glyphicon glyphicon-ok"></i>
          Tasks </a>
        </li> -->
        <li>
        <%= link_to followers_user_path(current_user) do %>
          <i class="glyphicon glyphicon-user"></i>
          Followers (<span class="followers_value"><%= @user.followers.count  %> </span> )
          <% end %>
        </li>
        <li>
        <%= link_to following_user_path(current_user) do %>
          <i class="glyphicon glyphicon-user"></i>
          Following ( <span class="following_value"> <%= @user.followings.count  %></span> )
          <% end %>
        </li>

        <li>
          <a href="#">
            <i class="glyphicon glyphicon-flag"></i>
            Help </a>
          </li>
        </ul>
      </div>
      <!-- END MENU -->
    </div>
    <div>
      <%=render 'shared/following_list'  %>
    </div>

app/views/shared/_signup_form.html.erb
<h2>Signup</h2>
    <%= form_for(@user ||= User.new) do |f| %>
    <%= render 'shared/error_messages',object: f.object %>

    <%=f.label :name %>
    <%=f.text_field :name, class: 'form-control' %>

    <%=f.label :email %>
    <%=f.email_field :email, class: 'form-control'%>

    <%=f.label :password %>
    <%=f.password_field :password, class: 'form-control' %>

    <%=f.label :confirm_password ,"Confirmation"%>
    <%=f.password_field :confirm_password, class: 'form-control' %>

    <%= f.submit "Create my account", class: "btn btn-primary submit-button" %>

    <% end %>

app/views/shared/_thoughts_feed.html.erb
<div class="home-feed" >
<ol  class="well">
<div class="feed-title "> <%= action_name.capitalize  %> </div>
<%= render @feed  %>
</ol>
<%= will_paginate @feed   %>
</div>

app/views/shared/_thoughts_form.html.erb
  <%= form_for(@thought ||= Thought.new ) do |f| %>
  <%= render 'shared/error_messages',object:f.object  %>
    <%=f.label :content ,"Thoughts"%>
  <div class="category">
    <%= f.collection_select :category, Thought.select("DISTINCT(thoughts.category),thoughts.category").
    reorder(:category),:category, :category  %>
  </div>
    <%= f.text_field :title, placeholder: "Title..." , class: "form-control "%>
  <div >
    <%= f.text_area :content, placeholder: "Write..." , class: "form-control "%>
  </div>

<%= f.text_field :tag_list, 'data-role'=>'tagsinput'  %>
  <section  class="post-button">
    <%= f.submit "Post", class: "btn btn-success btn-sm btn-block thought-button" %>
  </section>
  <div id="visibility-point">
  </div>
<% end %>


<script>
var valueToSelect= "<%= action_name.capitalize  %>"
function SelectElement(valueToSelect)
{
    var element = document.getElementById('thought_category');
    element.value = valueToSelect;
}
SelectElement(valueToSelect)
</script>