config/routes.rb
Rails.application.routes.draw do
  get 'personal' ,  to:  'static_pages#personal'
  get 'notes' , to: 'static_pages#notes'
  get 'diary' ,  to: 'static_pages#diary'
  post 'auth' , to: "static_pages#auth"
  resources :thoughts,only:[:edit,:create,:update,:destroy]
  resources :users do
    member do
      get :following,:followers
    end
  end
  resources :relationships, only: [:create,:destroy]
  post 'login' ,  to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  root 'static_pages#home'

  get 'help',   to:'static_pages#help'

  get 'about',  to: 'static_pages#about'

  get 'contact', to: 'static_pages#contact'

end

app/models/thought.rb
class Thought < ActiveRecord::Base
  belongs_to :user
  has_many :responses, dependent: :destroy
  has_many :response_thoughts, through: :responses, source: :resp
  has_many :tags, through: :additions, source: :resp
  default_scope -> { order(created_at: :desc) }
  validates :user_id,presence: true
  validates :content,presence: true
  validates :title,length: {maximum: 250}
  validates :category, presence: true

  def add_tags(tag_list)
    list=tag_list.split(",").map(&:to_i)
    if list.empty?
      return true if self.save
    else
      list.each do |tag|
        return false unless (Thought.exists?(tag) && self.save)
        # raise
        Response.create(thought_id: tag,resp_id: self.id)
      end
    end
  end

end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user,only: [:edit,:update,:destroy]

  def create
    thought=current_user.thoughts.build(thought_params)
    if thought.add_tags(params[:thought][:tag_list])
      flash[:info]="Thought has been added.."
    else
      flash[:danger]=" Unable to add thought"
    end
    redirect_to request.referrer ||root_url

  end

  def edit
    # @thought=Thought.find_by(id: params[:id])
    respond_to do |format|
      format.html {render 'shared/thoughts_form'}
      format.js
    end
  end

  def update
    if @thought.save
      flash[:info]= "Thought updated"
      redirect_to request.referrer
    end
  end

  def destroy
    @thought.destroy
    redirect_to :back
  end

  private

  def thought_params
    params.require(:thought).permit(:content,:tag_list,:category,:title)
  end

  def correct_user
    if @thought=Thought.find_by(id: params[:id])
    unless current_user == @thought.user
      flash[:danger]= "Not allowed "
      redirect_to root_url
    end
  else
    flash[:danger]= "Thought removed"
    redirect_to :back
  end
  end



end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/thoughts/_thought.html.erb
<li class="well thought-list" >
  <div class="thought-title">
    <% thought_title=thought.title %>
    <% if thought_title.empty? %>
Thought
    <% else %>
      <%= thought_title  %>
    <% end %>
    <span class="by-user">
       by <%= link_to thought.user.name,thought.user %>
    </span>
  </div>
  <div class="thought-content">
    <p>
      <%= thought.content  %>
    </p>
  </div>
  <div class="thought-options">
    <span class="thought-respond" data-id= "<%= thought.id %>" >
      <button class="btn btn-link "> Add thought </button>
    </span>
    <% if thought.user == current_user %>
    <span class="thought-edit-delete">
      <span class="dropdown">
        <button class="btn btn-link  dropdown-toggle" type="button" data-toggle="dropdown" type="button">Options</button>
        <ul class="dropdown-menu ">
          <li><%= link_to "Edit",edit_thought_path(thought),remote: true  %></li>
          <li><%= link_to "Delete",thought_path(thought) ,method: :delete ,data:{confirm:"Sure?"}%></li>
        </ul>
      </span>
    </span>
    <% end %>
      <span class="posted-time">
        Posted <%=  time_of_creation(thought.created_at) %>
      </span>
  </div>
</li>
<% responses=thought.response_thoughts %>
<% if responses.any? %>
<ol class="added-thoughts">
  <%= render responses  %>
</ol>
<% end %>

app/views/thoughts/edit.js.erb
$('.thought-column').html("<%= escape_javascript(render 'shared/thoughts_form') %>");
$('#thought_tag_list').tagsinput('add', '');
$(".bootstrap-tagsinput").find("input").removeAttr("placeholder");
$(".open .dropdown-toggle").dropdown("toggle");

app/views/thoughts/idex.html.erb
<h1>Thoughts#idex</h1>
<p>Find me in app/views/thoughts/idex.html.erb</p>

app/views/thoughts/new.html.erb
<h1>Thoughts#new</h1>
<p>Find me in app/views/thoughts/new.html.erb</p>

app/views/thoughts/show.html.erb
<h1>Thoughts#show</h1>
<p>Find me in app/views/thoughts/show.html.erb</p>