config/routes.rb
Rails.application.routes.draw do
  get 'personal' ,  to:  'static_pages#personal'
  get 'notes' , to: 'static_pages#notes'
  get 'diary' ,  to: 'static_pages#diary'
  post 'auth' , to: "static_pages#auth"
  resources :thoughts,only:[:edit,:create,:update,:destroy]
  resources :users do
    member do
      get :following,:followers
    end
  end
  resources :relationships, only: [:create,:destroy]
  post 'login' ,  to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  root 'static_pages#home'

  get 'help',   to:'static_pages#help'

  get 'about',  to: 'static_pages#about'

  get 'contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<section class="footer-bg">
  <small>
     QuickThoughts by
    <a href="https://in.linkedin.com/pub/rajeev-ramakrishnan/6a/547/312">Rajeev Ramakrishnan</a>
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path%></li>
      <li><a href="https://www.facebook.com/rajeevriitm" target="_blank">Facebook</a></li>
    </ul>
  </nav>
  </section>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">

  <div class="container-fluid" id="header">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
      data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
  </button>
  <div id="logo">
      <%= link_to("QuickThoughts", root_path , class: "navbar-brand") %>
  </div>
</div>
<% if logged_in? %>
    <%= render 'layouts/logged_in_header' %>
<% else %>
    <%= render 'layouts/nonlogged_in_header' %>
<% end  %>
</div>

</nav>

app/views/layouts/_logged_in_header.html.erb
<div class="collapse navbar-collapse">

  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Home",root_url %></li>
    <li><%= link_to "Personal", personal_url %></li>
    <li><%= link_to "Diary", diary_url %></li>
    <li><%= link_to "Notes", notes_url %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Account Settings","#" %></li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <li class="divider"></li>
        <li><%= link_to "Help","#"  %></li>
      </ul>
    </li>
    <div class=" pull-right search-type">

      <%= form_tag users_path,role: "search",method: :get do %>
      <div class="input-group">
      <%= text_field_tag :search ,nil,class: "form-control typeahead", placeholder: "Search"%>
          <div class="input-group-btn">
            <button class="btn btn-default " type="submit"><i class="glyphicon glyphicon-search"></i></button>
          </div>
      </div>
      <% end %>

<!--       <form class="navbar-form" role="search">
        <div class="input-group">
          <input class="form-control typeahead" placeholder="Search" name="srch-term" id="srch-term" type="text">
          <div class="input-group-btn">
            <button class="btn btn-default " type="submit"><i class="glyphicon glyphicon-search"></i></button>
          </div>
        </div>
      </form>
    -->
  </div>
<li class="how-to">
  <button type="button" class="btn btn-info btn-sm navbar-btn">How to</button></li>
  <li>
  </ul>
</div>

app/views/layouts/_nonlogged_in_header.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

<%= form_for(:session,url: login_path,html: {id: "signin",  class: "navbar-form navbar-right" , role: "form"}) do |f| %>
<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <%=f.email_field :email, class: 'form-control', placeholder:"Email" %>
</div>

<div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
  <%=f.password_field :password, class: 'form-control', placeholder: "Password" %>
</div>
<div class="input-group" id="remember">
<%= f.label :remember,"Remeber me?" %>
<%= f.check_box :remember %>
<br/>
<section class="forgot" >
<%= link_to "Forgot password?","#"  %>
</section>
</div>
<%= f.submit "Login", class: "btn btn-primary" %>
<% end %>

</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title_display(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class= "main-body">
    <div class="container-fluid " >
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> flash">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span></button>

      <%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </div>
</body>
</html>